Embetter test case runner.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -16,6 +16,23 @@
 
 set -u
 
+################################# Test Cases #################################
+imgcat_tests() {
+    #           command that should succeed
+    assert_ok   imgcat --width=12 Xterm_256color_chart.png
+
+    #           expected output     command
+    assert_eq   1px_256_table.out   imgcat -d 256 1px_256_table.png
+    assert_eq   1px_8_table.out     imgcat -d 8 1px_8_table.png
+
+    #           command that should fail
+    assert_fail imgcat --width=-3 "$ANY_IMAGE"
+    assert_fail imgcat -w mank3y "$ANY_IMAGE"
+}
+
+
+############################### Test Framework ###############################
+
 # Parallel arrays of invocations (the command line), and its output.
 declare -a INVOCATIONS
 declare -a OUTPUT
@@ -24,85 +41,90 @@ declare -a STDERR
 # Array of indices to invocations, output, stderr.
 declare -a FAILURES
 
-IMGCAT="$(realpath "$1")"
-
 ORIGINAL_DIR="$(pwd)"
 SCRIPT_DIR="$(dirname "$0")"
 
-_assert() {
-  local output stderr bin
-  local -i status
-  bin="${1/imgcat/$IMGCAT}"
-  shift
-  output="$(mktemp)"
-  stderr="$(mktemp)"
+# Get the absolute path to the given binary
+IMGCAT="$(realpath "$1")"
+ANY_IMAGE=1px_8_table.png
 
-  # || : prevents this from exiting prematurely
-  "$bin" "$@" >"$output" 2>"$stderr"
-  status=$?
-  INVOCATIONS+=("$bin $*")
-  OUTPUT+=("$(cat "$output")")
-  STDERR+=("$(cat "$stderr")")
-
-  unlink "$output"
-  unlink "$stderr"
-
-  return $status
-}
-
-_add_failure() {
-  local -i items="${#INVOCATIONS[@]}"
-  FAILURES+=("$((items - 1))")
-}
+ANSI_RED="$(tput setaf 1)"
+ANSI_GRN="$(tput setaf 2)"
+ANSI_RST="$(tput sgr0)"
 
 assert_ok() {
-  _assert "$@" || _add_failure
+    _assert "$@" || _add_failure
+    return 0
 }
 
 assert_fail() {
-  _assert "$@" && _add_failure
+    _assert "$@" && _add_failure
+    return 0
 }
 
 assert_eq() {
-  local expected="$1"; shift;
-  _assert "$@" || {
-    _add_failure
-    return
-  }
-  local -i last
-  last=$(( ${#OUTPUT[@]} - 1))
-  diff "$expected" - <<<"${OUTPUT[$last]}" >/dev/null || _add_failure
+    local expected="$1"; shift;
+    _assert "$@" || {
+        _add_failure
+        return 0
+    }
+
+    local -i last
+    last=$(( ${#OUTPUT[@]} - 1))
+    diff "$expected" - <<<"${OUTPUT[$last]}" >/dev/null || _add_failure
+    return 0
+}
+
+_assert() {
+    local output stderr bin
+    local -i status
+    bin="${1/imgcat/$IMGCAT}"
+    shift
+    output="$(mktemp)"
+    stderr="$(mktemp)"
+
+    # Run the command
+    "$bin" "$@" >"$output" 2>"$stderr"
+    status=$?
+    INVOCATIONS+=("$bin $*")
+    OUTPUT+=("$(cat "$output")")
+    STDERR+=("$(cat "$stderr")")
+
+    unlink "$output"
+    unlink "$stderr"
+
+    return $status
+}
+
+_add_failure() {
+    local -i items="${#INVOCATIONS[@]}"
+    FAILURES+=("$((items - 1))")
 }
 
 print_success() {
-  echo "$ncases tests passed"
+    echo "${ANSI_GRN}$ncases tests passed${ANSI_RST}"
 }
 
 print_failures() {
-  for index in "${FAILURES[@]}"; do
-    echo "Failed: ${INVOCATIONS[$index]}"
-    echo "=== stderr ==="
-    echo "${STDERR[$index]}"
-    echo "=== output ==="
-    echo "${OUTPUT[$index]}"
-  done
+    for index in "${FAILURES[@]}"; do
+        echo "Failed: ${INVOCATIONS[$index]}"
+        echo "=== stderr ==="
+        echo "${STDERR[$index]}"
+        echo "=== output ==="
+        echo "${OUTPUT[$index]}"
+    done
 
-  echo
-
-  echo "Failures:   $nfailures"
-  echo "Tests:      $ncases"
+    echo "${ANSI_RED}$nfailures/$ncases tests failed${ANSI_RST}"
 }
 
 # Run the tests in test-cases
-cd "$SCRIPT_DIR" || exit -1
-source test-cases.sh || exit -1
-cd "$ORIGINAL_DIR" || exit -1
+cd "$SCRIPT_DIR" && imgcat_tests && cd "$ORIGINAL_DIR" || exit -1
 
 declare -i nfailures="${#FAILURES[@]}"
 declare -i ncases="${#INVOCATIONS[@]}"
 if ((nfailures > 0)); then
-  print_failures
-  exit -1
+    print_failures
+    exit -1
 else
-  print_success
+    print_success
 fi
